[general]
flip_aug = false
#shuffle_caption = true
caption_extension = ".txt"
enable_bucket = true
bucket_no_upscale = false
max_bucket_reso = 2048
#batch_size = 1
keep_tokens = 1
#caption_dropout_rate = 0.05

[[datasets]]
resolution = [1024, 1024]

  [[datasets.subsets]]
  image_dir = "/home/en1u2/AI-Stuff/References/latest"
  num_repeats = 8
